// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGos4BpAB-heRs5F57HAEBhdQpYCi5rwA',
    appId: '1:1089902879044:web:c08e0042c05b2e012c3711',
    messagingSenderId: '1089902879044',
    projectId: 'sosegi-70ec4',
    authDomain: 'sosegi-70ec4.firebaseapp.com',
    storageBucket: 'sosegi-70ec4.firebasestorage.app',
    measurementId: 'G-GNW1609DTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3C6EtDQivEOhID4hcstl2sTbQ1f177lA',
    appId: '1:1089902879044:android:93cee246b2ae82a62c3711',
    messagingSenderId: '1089902879044',
    projectId: 'sosegi-70ec4',
    storageBucket: 'sosegi-70ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT758A6i35zAtz55ExetIZ21TpKR9YVjk',
    appId: '1:1089902879044:ios:e998592d582dd0402c3711',
    messagingSenderId: '1089902879044',
    projectId: 'sosegi-70ec4',
    storageBucket: 'sosegi-70ec4.firebasestorage.app',
    iosClientId: '1089902879044-6kvgcvv72ihgjemsb753ncrqmd28sd9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieumProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT758A6i35zAtz55ExetIZ21TpKR9YVjk',
    appId: '1:1089902879044:ios:e998592d582dd0402c3711',
    messagingSenderId: '1089902879044',
    projectId: 'sosegi-70ec4',
    storageBucket: 'sosegi-70ec4.firebasestorage.app',
    iosClientId: '1089902879044-6kvgcvv72ihgjemsb753ncrqmd28sd9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieumProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGos4BpAB-heRs5F57HAEBhdQpYCi5rwA',
    appId: '1:1089902879044:web:9a028ba93457c4e22c3711',
    messagingSenderId: '1089902879044',
    projectId: 'sosegi-70ec4',
    authDomain: 'sosegi-70ec4.firebaseapp.com',
    storageBucket: 'sosegi-70ec4.firebasestorage.app',
    measurementId: 'G-T2W30K5GL3',
  );
}
